In [1]:
import numpy as np

In [2]:
# 1D array
myarr = np.array([4,56,8,3], np.int8)

In [3]:
myarr

array([ 4, 56,  8,  3], dtype=int8)

In [4]:
# myarr1 = np.array([4,56666666,8,3], np.int8)

In [5]:
# myarr1

In [6]:
myarr[0]

4

In [7]:
# 2D array
myarr = np.array([[4,56,8,3]], np.int8)

In [8]:
myarr[0,1]                                                                                           

56

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int8')

In [11]:
# to change the element value
myarr[0,2] = 45

In [12]:
myarr

array([[ 4, 56, 45,  3]], dtype=int8)

In [13]:
listarray = np.array([[1,2,3],[5,7,8],[9,6,2]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 7, 8],
       [9, 6, 2]])

In [15]:
listarray.size

9

In [16]:
np.array({5,7,9})

array({9, 5, 7}, dtype=object)

In [19]:
zeros = np.zeros((3,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
#arange 
rng = np.arange(12)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
#lnspace start,end,no of equallu linearly space element
lnspace = np.linspace(1,3,12)

In [25]:
lnspace

array([1.        , 1.18181818, 1.36363636, 1.54545455, 1.72727273,
       1.90909091, 2.09090909, 2.27272727, 2.45454545, 2.63636364,
       2.81818182, 3.        ])

In [28]:
lnspace = np.linspace(1,4,4)

In [29]:
lnspace

array([1., 2., 3., 4.])

In [30]:
emp = np.empty((4,6))

In [31]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56602523e-307, 1.29061821e-306,
        1.37961234e-306, 9.34598926e-307, 1.33511562e-306],
       [9.34600963e-307, 8.45559303e-307, 8.06613465e-308,
        6.89810244e-307, 1.22387550e-307, 2.22522596e-306]])

In [33]:
emp_like = np.empty_like(lnspace)

In [34]:
emp_like

array([1., 2., 3., 4.])

In [35]:
ide = np.identity(45)

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)

In [43]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [45]:
ar = np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
arr.ndim

1

In [54]:
ar.size

9

In [55]:
ar.nbytes

36

In [56]:
one = np.array([1,2,3,4,5])

In [57]:
one.argmax()

4

In [58]:
one.argmin()

0

In [60]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [61]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [62]:
ar.argmax()

6

In [63]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [65]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [66]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [67]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [68]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [69]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [70]:
ar.sum()

29

In [71]:
ar.max()

7

In [72]:
ar.min()

0

In [73]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [74]:
np.count_nonzero(ar)

8

In [78]:
ar[1,2] = 0

In [80]:
ar.nonzero()

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [81]:
import sys

In [82]:
py_ar = [0,4,55,2]

In [84]:
np_ar = np.array(py_ar)

In [85]:
sys.getsizeof(1)*len(py_ar)

112

In [87]:
np_ar.itemsize* np_ar.size

16