In [1]:
import numpy as np

In [2]:
arr = np.arange(100000)

In [3]:
pythlist= list(range(100000))

In [4]:
%time for _ in range(10):[item*3 for item in pythlist]
    

CPU times: total: 62.5 ms
Wall time: 59.9 ms


In [5]:
%time for _ in range(10): arr = arr*3
    

CPU times: total: 0 ns
Wall time: 996 µs


In [6]:
np.array([3,5,6,7,4])

array([3, 5, 6, 7, 4])

In [7]:
import numpy as np
array1 = np.array([[3,4.5,1,2],[1,3,5,7]], dtype='int32')
print(array1)

[[3 4 1 2]
 [1 3 5 7]]


In [8]:
array1.shape

(2, 4)

In [9]:
array1.dtype

dtype('int32')

In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60216183e-306,
        7.56602523e-307, 3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 6.23036978e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        9.34593493e-307, 7.56602524e-307, 2.22522596e-306]])

In [12]:
array1

array([[3, 4, 1, 2],
       [1, 3, 5, 7]])

In [13]:
array1*array1

array([[ 9, 16,  1,  4],
       [ 1,  9, 25, 49]])

In [14]:
array1**array1

array([[    27,    256,      1,      4],
       [     1,     27,   3125, 823543]])

In [15]:
np.array([12.0**12])

array([8.91610045e+12])

In [16]:
1/array1

array([[0.33333333, 0.25      , 1.        , 0.5       ],
       [1.        , 0.33333333, 0.2       , 0.14285714]])

# slicing

In [17]:
array1

array([[3, 4, 1, 2],
       [1, 3, 5, 7]])

In [18]:
array1[4:6]

array([], shape=(0, 4), dtype=int32)

In [19]:
array2 = np.array([2,4,5,6,34,7,9])

In [20]:
arr2 = array2[2:4].copy()

In [21]:
arr2

array([5, 6])

In [22]:
arr2[0] = 3

In [23]:
array2

array([ 2,  4,  5,  6, 34,  7,  9])

In [24]:
array1

array([[3, 4, 1, 2],
       [1, 3, 5, 7]])

In [25]:
array1[0,2]

1

In [26]:
import numpy as np

In [27]:
a = np.arange(6)

In [28]:
a

array([0, 1, 2, 3, 4, 5])

In [29]:
b = np.array([1,3,4,5,6,12,45,3,4,45,6,7,8,3,8,34,32,54])
b = b.reshape(6,3)

In [30]:
b

array([[ 1,  3,  4],
       [ 5,  6, 12],
       [45,  3,  4],
       [45,  6,  7],
       [ 8,  3,  8],
       [34, 32, 54]])

In [34]:
np.argsort(b, axis=0)

array([[0, 0, 0],
       [1, 2, 2],
       [4, 4, 3],
       [5, 1, 4],
       [2, 3, 1],
       [3, 5, 5]], dtype=int64)

In [32]:
np.argmin(b)

0

In [33]:
np.argmax(b)

17