In [1]:
import numpy as np
data=np.array([[1,4,6],[6,7,8]])

In [2]:
data*10

array([[10, 40, 60],
       [60, 70, 80]])

In [3]:
data+data

array([[ 2,  8, 12],
       [12, 14, 16]])

In [4]:
# ndarray is a multidimentional container for homogeneous data
data.shape 

(2, 3)

In [5]:
# dtype: an object describing the data type of the array
data.dtype 

dtype('int32')

In [6]:
# creating ndarray
data1=[8,4,5.6,0,3]

In [7]:
arr1=np.array(data1) 

In [8]:
arr1

array([8. , 4. , 5.6, 0. , 3. ])

In [9]:
# nested sequence a list of equal-length lists will be converted into a multidimensional array
data2=[[1,2,3,4],[5,6,7,8]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# dimension
arr2.ndim

2

In [13]:
# passed tuple
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
# 0's
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
# creates an array without initializing its values to any particular value
np.empty((3,2, 6))

array([[[1.00415202e-311, 1.00412829e-311, 1.00417260e-311,
         1.00418173e-311, 1.00418173e-311, 1.00418173e-311],
        [1.00418171e-311, 1.00418171e-311, 1.00417260e-311,
         1.00417260e-311, 1.00418171e-311, 1.00418171e-311]],

       [[1.00417260e-311, 1.00416804e-311, 1.00416804e-311,
         1.00418173e-311, 1.00418173e-311, 1.00418173e-311],
        [1.00418173e-311, 1.00418173e-311, 1.00418173e-311,
         1.00418173e-311, 1.00418173e-311, 1.00418173e-311]],

       [[1.00418174e-311, 1.00418173e-311, 1.00418173e-311,
         1.00418173e-311, 1.00418174e-311, 1.00418174e-311],
        [1.00418174e-311, 1.00418174e-311, 1.00418174e-311,
         1.00418174e-311, 1.00418174e-311, 1.00418174e-311]]])

In [19]:
# arrange is an array valued version of the built in python range fundction
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# data types or dtypes
# dtypes are part of what make numpy so powerful and flexible

In [21]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [22]:
# you dan explicitly convert or cast an array from one dtype to another using ndarrays astype method
float_arr = arr.astype(np.float64)

In [23]:
float_arr.dtype

dtype('float64')

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
arr1 =np.array([3.4,-1.4,-5.3,0.6,10.1])

In [26]:
arr1.astype(np.int32)

array([ 3, -1, -5,  0, 10])

In [27]:
int_array = np.arange(10)

In [28]:
calibers = np.array([.22,.279,.357,.44], dtype=np.float64)

In [29]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
# array operation
arr = np.array([[1,2,3],[4,5,6]])

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
# array indexing and slicing
# 1 d array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
# slicing
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8]=12

In [40]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr[5:8]=12,4,5

In [42]:
arr

array([ 0,  1,  2,  3,  4, 12,  4,  5,  8,  9])

In [43]:
arr_slice =arr[5:8]

In [44]:
arr_slice[1]=12345

In [45]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,     5,     8,
           9])

In [46]:
arr_slice[:]=64

In [47]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
aer=arr[5:8].copy()

In [49]:
aer

array([64, 64, 64])

In [50]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [51]:
# 2D array
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr2d[2]

array([7, 8, 9])

In [53]:
arr2d[0][2]

3

In [54]:
arr2d[0,2]

3

In [55]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# 3d array 2x2x3

In [57]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [58]:
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [61]:
old_values = arr3d[0].copy

In [62]:
old_values

<function ndarray.copy>

In [63]:
arr3d[0]=42

In [64]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
# arr3d[0] = old_values

In [66]:
arr3d[1,0]

array([7, 8, 9])

In [67]:
# indexing and slicing

In [68]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [69]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# multiple slices and indexes
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [73]:
arr2d[1,:2]

array([4, 5])

In [74]:
arr2d[2,:1]

array([7])

In [75]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [76]:
arr2d[:2, 1:] = 0

In [77]:
# boolean indexing
from numpy.random import randn 


In [78]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [79]:
data = randn(7,4)

In [80]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [81]:
data

array([[ 1.34654141,  0.10625765, -1.15880268,  1.37746844],
       [ 1.30549815, -0.91182733,  0.27353471,  0.24152009],
       [-0.49552695, -2.46724457, -0.20720818, -0.52853485],
       [ 0.36053072, -0.30635444,  0.05333175,  0.09638441],
       [-0.0756309 ,  0.20669966, -0.73799447, -0.85661465],
       [ 0.10416359,  0.99619439,  0.69216228,  0.89858256],
       [-1.10013127, -0.57293934,  0.37459525,  0.64340608]])

In [82]:
# 3x3 matrix
# arr[:2,1:]  (2,2)
# arr[2]      (3,)
# arr[2,:]    (1,3)
# arr[:,:2]    (3,2)
# arr[1,:2]    (2,)
# arr[1:2, :2]  (1,2)

In [83]:
# suppose each name corresponds to a row in the data array , if we wanted to select all the rows with corresponding name 'bob' such as ==asign with arrays are also vectorized 
# thus comparing names with the string 'bob' yields a boolean array

In [84]:
names == 'Bob'


array([ True, False, False,  True, False, False, False])

In [85]:
# this boolean array can passed when indexing the array 
data[names == 'Bob']

array([[ 1.34654141,  0.10625765, -1.15880268,  1.37746844],
       [ 0.36053072, -0.30635444,  0.05333175,  0.09638441]])

In [86]:
# the boolean array must be the same length as the axis its indexing here 7 indexing and 7 rowsd
# you can mix and match boolean arrays with slicers or integers

In [87]:
data[names == 'Bob', 2:]

array([[-1.15880268,  1.37746844],
       [ 0.05333175,  0.09638441]])

In [88]:
data[names == 'Bob', 3]

array([1.37746844, 0.09638441])

In [89]:
# to select everything but 'Bob', you can either use != or negate the condition using
names != 'Bob'


array([False,  True,  True, False,  True,  True,  True])

In [90]:
data[~(names == 'Bob')]

array([[ 1.30549815, -0.91182733,  0.27353471,  0.24152009],
       [-0.49552695, -2.46724457, -0.20720818, -0.52853485],
       [-0.0756309 ,  0.20669966, -0.73799447, -0.85661465],
       [ 0.10416359,  0.99619439,  0.69216228,  0.89858256],
       [-1.10013127, -0.57293934,  0.37459525,  0.64340608]])

In [91]:
# selecting two of the three names to combine multiple boolean conditions, use boolean arithmetic operators like &(and) and | (or)

In [92]:
mask = (names == 'Bob') | (names =='Will')

In [93]:
mask

array([ True, False,  True,  True,  True, False, False])

In [94]:
data[mask]

array([[ 1.34654141,  0.10625765, -1.15880268,  1.37746844],
       [-0.49552695, -2.46724457, -0.20720818, -0.52853485],
       [ 0.36053072, -0.30635444,  0.05333175,  0.09638441],
       [-0.0756309 ,  0.20669966, -0.73799447, -0.85661465]])

In [95]:
# selecting data from an array by boolean indexing always creates a copy of the data, even if the returned arrays is unchanged
data

array([[ 1.34654141,  0.10625765, -1.15880268,  1.37746844],
       [ 1.30549815, -0.91182733,  0.27353471,  0.24152009],
       [-0.49552695, -2.46724457, -0.20720818, -0.52853485],
       [ 0.36053072, -0.30635444,  0.05333175,  0.09638441],
       [-0.0756309 ,  0.20669966, -0.73799447, -0.85661465],
       [ 0.10416359,  0.99619439,  0.69216228,  0.89858256],
       [-1.10013127, -0.57293934,  0.37459525,  0.64340608]])

In [96]:
# to set all of the negative values in data to 0 we need only
data[data< 0]= 0

In [97]:
data

array([[1.34654141, 0.10625765, 0.        , 1.37746844],
       [1.30549815, 0.        , 0.27353471, 0.24152009],
       [0.        , 0.        , 0.        , 0.        ],
       [0.36053072, 0.        , 0.05333175, 0.09638441],
       [0.        , 0.20669966, 0.        , 0.        ],
       [0.10416359, 0.99619439, 0.69216228, 0.89858256],
       [0.        , 0.        , 0.37459525, 0.64340608]])

In [98]:
data[data>0]= 0

In [99]:
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
# setting whole rows or columns using a 1d boolean array 

In [101]:
data[names != 'Joe'] = 7

In [102]:
data

array([[7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
# fancy indexing
# indexing using integer arrays


In [104]:
arr = np.empty((8,4))

In [105]:
arr

array([[1.00413539e-311, 1.03259720e-321, 0.00000000e+000,
        0.00000000e+000],
       [2.33419537e-312, 5.02034658e+175, 2.10621009e-076,
        1.79493860e-052],
       [2.27285048e+184, 8.98498477e-067, 3.92349220e-033,
        2.16385130e+190],
       [1.94918964e-153, 5.30581644e+180, 4.32453723e-096,
        2.14027814e+161],
       [1.47762371e+248, 4.30625279e-096, 4.82337723e+228,
        4.55883645e-037],
       [9.72163473e-072, 1.78636863e-051, 7.40813538e-038,
        4.26399447e-096],
       [1.16097020e-028, 1.26071127e-076, 2.54818287e-028,
        3.69286170e-057],
       [1.04917184e-153, 9.08366791e+223, 6.14415221e-144,
        2.41907536e-312]])

In [106]:
for i in range(8):
    arr[i] = i

In [107]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [108]:
# to select out a subset of the rows in a particular order you can simply pass a list or ndarray of integers specifying the desired order
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [109]:
# Using negative indices select rows from the end 
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [110]:
# passing multiple index arrays does something slightly different it selects a 1d array of element corresponding to each tuple of indices 
arr = np.arange(32).reshape((8,4))

In [111]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
# location of element [columns],[rows] index (1,0),(3,2), ....
arr[[1,3,4,6],[0,2,3,3]]

array([ 4, 14, 19, 27])

In [113]:
# the rectangular region formed by selecting a subset of the matrix rows and columns 

In [114]:
arr[[1,5,7,2]][[0,3,1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

<!-- or -->


In [115]:
# or
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [116]:
# in fancy indexing unlike slicing always copies the data into a new array

In [117]:
# transporting Arrays and swapping axes

In [118]:
# tranposing is a special form of reshaping which similarly returns a view on the underlying data without copying anything 
# arrays have the transpose method and also the special T atribute


In [119]:
arr = np.arange(15).reshape((3,5))

In [120]:
arr     

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [122]:
# inner matrix products xtx using np.dot

In [123]:
arr = np.random.randn(6,3)

In [124]:
arr

array([[ 0.93435686, -0.99706656, -1.23871079],
       [-0.97839472,  0.67531932,  0.21637967],
       [ 0.89992297, -1.57887584, -0.1793979 ],
       [ 0.21673803,  0.37076489,  1.50157113],
       [-0.53168349, -1.40855582, -0.30396791],
       [ 0.51830423,  0.51979397, -0.31217571]])

In [125]:
np.dot(arr.T, arr)

array([[ 3.23844228, -1.91453533, -1.20528664],
       [-1.91453533,  6.33472869,  2.48706806],
       [-1.20528664,  2.48706806,  4.05797422]])

In [126]:
# transpose will accept a tuple of axis numbers to permute the axes 

In [127]:
arr = np.arange(16).reshape((2,2,4))

In [128]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [129]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [130]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [131]:
# .T is just a special case of swaping axes ndarray has the method swapaxes which takes a pair of axis numbers
# swapaxes similarly return a view on the data without making a copy
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [132]:
# universal functions : Fast element-wise Array functions
# ufunc is  a function that performs elementwise operations on data in ndarrays

In [133]:
arr = np.arange(10)

In [134]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [136]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [137]:
# unary ufunction such as add maximum take 2 arrays and return a single array as the result
x=randn(8)

In [138]:
x

array([-0.59844361, -0.48701756,  1.48601028, -0.8629624 , -0.35369033,
        2.22029508,  0.72600179, -0.20260129])

In [139]:
y=randn(8)

In [140]:
y

array([ 0.62005848,  0.07943536, -1.09385828, -0.81443393, -0.50572431,
        1.17783367,  1.65083902,  1.69769289])

In [141]:
np.maximum(x,y)

array([ 0.62005848,  0.07943536,  1.48601028, -0.81443393, -0.35369033,
        2.22029508,  1.65083902,  1.69769289])

In [142]:
# while not common a ufunc can returnmultiple  arrays , avector version of the built in python divmod
arr = randn(7)*5

In [143]:
arr

array([  8.08870268, -12.25944217,  -0.57314095,  -2.24393352,
         0.98859989,  -3.29923503,   4.25354954])

In [144]:
np.modf(arr)

(array([ 0.08870268, -0.25944217, -0.57314095, -0.24393352,  0.98859989,
        -0.29923503,  0.25354954]),
 array([  8., -12.,  -0.,  -2.,   0.,  -3.,   4.]))

In [145]:
# using numpy arrays enables you to express many kinds of data processing tasks as concise array expressions that might otherwise require writing loops
the practice of replacing explit loop with array ex

SyntaxError: invalid syntax (2130815648.py, line 2)